sudo: required
services:
  - docker

before_install:
  - docker build -t lczmdr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lczmdr/react-test npm test -- --coverage

after_success:
  - docker build -t lczmdr/multi-client ./client
  - docker build -t lczmdr/multi-nginx ./nginx
  - docker build -t lczmdr/multi-server ./server
  - docker build -t lczmdr/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and 
  - docker push lczmdr/multi-client:latest
  - docker push lczmdr/multi-nginx:latest
  - docker push lczmdr/multi-server:latest
  - docker push lczmdr/multi-worker:latest